from pathlib import Path
import re,json,html
P=Path(__file__).parent
original=(P/'templates/original.html').read_text()
def esc(s): return html.escape(s,quote=True)
WA='https://wa.me/85262568419?text=Hi%20Dick%2C%20I%27d%20like%20to%20discuss%20a%20hardware%20project.'
LI='https://www.linkedin.com/in/dick-chi-wai-mui-pmp-certified-357661b6'
nav=[('How I Help','/#services'),('Selected Work','/#work'),('Asia Network','/#network'),('Insights','/insights'),('About','/#about'),('Partners','/partners')]
def link(text,url,cls='',extra=''): return f'<a class="{cls}" href="{url}" {extra}>{text}</a>'
def cta(text='Start a Project',query=''): return link(text,'/start-a-project'+query,'button button-primary')
def heading(title,sub='',eye=''): return f'<div class="section-heading"><div><p class="eyebrow">{eye}</p><h2>{title}</h2></div><p>{sub}</p></div>'
def section(id,title,content,sub='',eye=''): return f'<section class="section-shell section" id="{id}">{heading(title,sub,eye)}{content}</section>'
def grid(cards,cls='three-grid'): return f'<div class="{cls}">'+''.join(cards)+'</div>'
def card(title,body): return f'<article class="content-card"><h3>{title}</h3>{body}</article>'
header=f'''<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="Dick Mui home"><span class="brand-mark">DM</span><span>Dick Mui</span></a><a class="mobile-project" href="/start-a-project">Start a Project</a><button class="menu-button" aria-label="Open navigation" aria-controls="primary-nav" aria-expanded="false">Menu</button><nav class="nav" id="primary-nav" aria-label="Primary navigation">{''.join(link(t,u) for t,u in nav)}{link('Start a Project','/start-a-project','nav-cta')}</nav></header>'''
footer=f'''<footer class="site-footer section-shell"><div><span class="brand-mark small">DM</span><strong>Dick Mui Consulting</strong></div><p>Hardware Commercialization | NPI | Asia Manufacturing | Program Leadership</p><nav aria-label="Footer">{''.join(link(t,u) for t,u in nav)}{link('Start a Project','/start-a-project')}</nav><p>{link('LinkedIn',LI)} · {link('WhatsApp',WA)} · {link('Privacy Policy','/privacy')}</p><p>UK-based · Working across UK / EU / US and Asia</p><!-- TODO: Add verified legal entity details if applicable. No public email supplied. --></footer>'''
def page(path,title,description,body,noindex=False,schema=None):
    url='https://dickmui-consulting.vercel.app'+('/' if path=='index' else '/'+path)
    if path != 'index': body = body.replace('<h2>', '<h1 class="page-title">', 1).replace('</h2>', '</h1>', 1)
    out=P/(path+'.html'); out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(description)}"><link rel="canonical" href="{url}"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="{url}"><meta property="og:image" content="https://dickmui-consulting.vercel.app/social-card.png"><meta name="twitter:card" content="summary_large_image">{'<meta name="robots" content="noindex,follow">' if noindex else ''}<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">{json.dumps(schema or {'@context':'https://schema.org','@type':'WebPage','name':title,'url':url})}</script></head><body>{header}<main id="main">{body}</main>{footer}<script src="/script.js" defer></script></body></html>''')
# Existing visual and copy retained where the brief does not replace them.
hero=re.search(r'<section class="hero section-shell">.*?</section>',original,re.S)[0]
hero=hero.replace('Turning concepts into <span>scalable hardware.</span>','Hardware stuck between <span>design and production?</span>').replace('I help UK, EU and US product teams move from design intent to reliable production—aligning engineering, suppliers, cost, quality and schedule across Asia.','I help UK, EU and US product teams de-risk suppliers, tooling, NPI and production across Asia — from prototype through mass production.').replace('href="#contact">Discuss your project','href="/start-a-project">Start a Project').replace('href="#process">See how I work','href="/#services">See How I Help')
hero=re.sub(r'<div class="proof-strip".*?</div>\s*</div>\s*</div>', '<p class="credibility">20+ Years Hardware &amp; Operations · PMP · UK-Based · Asia-Connected</p></div>',hero,flags=re.S)
problems=[('My project is delayed','Supplier responses, engineering decisions or corrective actions are not closing fast enough.','Recover the Program','recovery'),('I need the right manufacturer','I need sourcing and technical qualification — not another supplier list.','Find the Right Fit','dfm'),("We’re approaching Pilot / MP",'I need confidence that tooling, quality, assembly and production are actually ready.','De-risk Production','quality'),("Cost or tooling doesn’t make sense",'Supplier quotations, DFM assumptions, MOQ or tooling costs need independent review.','Review the Commercials','dfm')]
problem=section('problems','What brought you here?',grid([f'<a class="content-card problem-card" href="/#service-{i}"><h3>{t}</h3><p>{b}</p><strong>{c} →</strong></a>' for t,b,c,i in problems],'four-grid'),'Hardware programs rarely fail because of one big issue. They usually get stuck between decisions, suppliers, engineering and production.','Start with your constraint')
services=[('npi','Commercialization &amp; NPI','A promising prototype needs a controlled path to production.','I align requirements, ownership and build decisions.','A clear sequence of evidence and gates for the next build.','Stage-gate planning · Requirements & ownership · Launch readiness'),('dfm','DFM &amp; Supplier Strategy','Quotes and manufacturing assumptions are difficult to compare.','I challenge process, tooling, cost and supplier fit.','A clearer basis for supplier and commercial decisions.','RFQ structure · Supplier qualification · Cost / MOQ / lead-time trade-offs'),('recovery','Program Recovery','Delays and unresolved actions are blocking the next milestone.','I establish owners, decisions and supplier accountability.','A practical recovery path with visible priorities.','Risk triage · Corrective-action tracking · Executive reporting'),('quality','Quality &amp; Production Readiness','A passed build does not establish production readiness.','I define verification, corrective-action and release gates.','Production decisions grounded in evidence.','Pilot & OQC plans · Acceptance criteria · Packaging & shipment readiness')]
service=section('services','How I Help',grid([f'<article class="service-card {"featured" if n==0 else ""}" id="service-{i}"><div class="card-index">0{n+1}</div><h3>{t}</h3><p><b>Problem</b> {p}</p><p><b>My role</b> {r}</p><p><b>Outcome</b> {o}</p><details><summary>Explore the support</summary><p>{d}</p>{cta("Discuss this challenge", "?service="+i)}</details></article>' for n,(i,t,p,r,o,d) in enumerate(services)],'service-grid'),'Practical support across the decisions, suppliers and evidence that move hardware forward.')
cases=[{'slug':'production-readiness','title':'Production Readiness','challenge':'Pilot builds exposed recurring assembly and QA issues before production release.','role':'Defined corrective-action gates, QA verification requirements and production release criteria with the Asian manufacturing team.','outcome':'Production release was tied to objective verification rather than schedule pressure.'},{'slug':'supplier-dfm-review','title':'Supplier & DFM Review','challenge':'Multiple supplier quotations used different tooling, process and MOQ assumptions, making commercial comparison difficult.','role':'Normalised RFQ assumptions, challenged DFM decisions and reviewed manufacturing risk.','outcome':'Created a clearer supplier-selection and commercial decision framework.'},{'slug':'program-recovery','title':'Program Recovery','challenge':'A hardware program was losing time through slow supplier communication, unclear ownership and unresolved technical actions.','role':'Introduced action ownership, decision gates and structured supplier follow-up.','outcome':'Reduced ambiguity and created a clearer path toward the next build milestone.'}]
cases=json.loads((P/'data/case-studies.json').read_text())
def casebody(c): return ''.join(f'<p><strong>{k.title()}</strong><br>{c[k]}</p>' for k in ['challenge','role','outcome'])
workcards=grid([card(f'<span class="eyebrow">Case Study 0{n+1}</span><br>{esc(c["title"])}',casebody(c)+link('Read case study →','/work/'+c['slug'])) for n,c in enumerate(cases)])
work=section('work','Selected Work',workcards+link('View More Work →','/work','text-link'),'Examples of hardware commercialization challenges managed across supplier development, NPI, quality and production.','Anonymised experience')
process=re.search(r'<section class="section-shell section" id="process">.*?</section>',original,re.S)[0].replace('Decisions at the right time.','From uncertainty to controlled production')
artifacts=[('NPI Stage Gate','Requirements · Evidence · Decision','Agree what must be proven before the next commitment.'),('Supplier Scorecard','Capability · Risk · Fit','Compare suppliers against the needs of the program.'),('Risk Register','Risk · Owner · Mitigation','Make uncertainties and accountable owners visible.'),('Pilot Build Checklist','Build · Verify · Close','Track readiness and evidence before the pilot.'),('Corrective Action Tracker','Issue · Action · Verification','Close the cause, with evidence of the correction.'),('MP Release Gate','Quality · Supply · Release','Make the production decision against agreed criteria.')]
execution=section('execution','What good hardware execution looks like',grid([card(t,f'<div class="document-preview" aria-hidden="true"><span>ILLUSTRATIVE FORMAT</span><b>{s}</b><i></i><i></i><i></i></div><p>{b}</p>') for t,s,b in artifacts]),'Illustrative document formats showing structured execution. No confidential project documents are displayed.')
network=re.search(r'<section class="capability-section" id="network">.*?</section>',original,re.S)[0].replace('The right process—not just the nearest factory.','Asia Manufacturing Network').replace('I assemble fit-for-purpose manufacturing teams from a vetted network. Partner identities stay confidential until project fit and NDA terms are established.','Access is useful only when the right capability is matched to the right program. I work with manufacturing and technology partners across Asia based on technical, commercial and program fit.')
caps=['Injection Moulding','Tooling','CNC / Metal','PCBA / EMS','Final Assembly','Battery & Power','Display','Silicone / Elastomers','Testing & Compliance','Packaging','Logistics']
network=network.replace('</section>','<div class="section-shell"><div class="capability-tags">'+''.join(f'<span>{esc(x)}</span>' for x in caps)+'</div>'+cta('Discuss a Manufacturing Requirement','?service=dfm')+'</div></section>')
who=section('clients','Who I work with',grid([card(t,f'<p>{b}</p>') for t,b in [('Hardware Startups','Prototype through first production.'),('Scale-ups','Supplier, quality, cost and manufacturing challenges during growth.'),('Product Brands','Asia manufacturing execution and program leadership.'),('Engineering & Design Teams','Commercialization support when transitioning designs into scalable production.')]],'four-grid'))
about=re.search(r'<section class="about-section" id="about">.*?</section>',original,re.S)[0].replace('<div class="about-copy">','<div class="about-copy"><h3>Dick Mui, PMP</h3><p class="eyebrow">Hardware Commercialization &amp; Program Leader</p><!-- TODO: Insert approved real professional photograph here with descriptive alt text and explicit dimensions. -->').replace('<div class="principles">',link('Connect on LinkedIn →',LI,'text-link')+'<div class="principles">')
ways=section('ways','A practical way to start',grid([card('1. Project Discussion','<p>A short initial conversation to understand the product stage, problem and immediate constraints.</p>'+cta('Start a Conversation','?engagement=discussion')),card('2. Hardware Project Review','<p>A focused review of the program, supplier, quotation, DFM, production readiness or another defined problem.</p><p>Output may include key risks, observations, priority actions and recommended next steps.</p>'+cta('Request a Project Review','?engagement=review')),card('3. Embedded Program Support','<p>Ongoing support for supplier management, NPI, tooling, production readiness and cross-functional execution.</p>'+cta('Discuss Ongoing Support','?engagement=ongoing'))]))
independence='Partner participation does not determine project recommendations. Supplier and technology recommendations are based on project fit, capability, commercial requirements and execution risk.'
partner=section('partners','Selected Partner Network','<p>A selected network of manufacturing, technology and ecosystem partners supporting hardware commercialization across Asia.</p><!-- TODO: Only add approved partner names and logos with permission. -->'+f'<p class="independence">{independence}</p>'+link('Explore the Partner Network →','/partners','text-link'))
articles=[('supplier-mass-production','5 Signs Your Supplier Isn’t Ready for Mass Production'),('pilot-vs-mp','Pilot Build Passed — So Why Isn’t MP Ready?'),('compare-supplier-quotes','How to Compare China Supplier Quotes Properly'),('evt-dvt-pvt','EVT vs DVT vs PVT: What Actually Needs to Be Proven?'),('start-tooling','When Should a Hardware Startup Start Tooling?'),('cheap-tooling','Why Cheap Tooling Can Become Expensive Tooling')]
articles=[(a['slug'],a['title']) for a in json.loads((P/'data/insights.json').read_text())]
def articlecards(items): return grid([card(t,'<p class="eyebrow">Planned insight</p>'+link('View planned topic →','/insights/'+s)) for s,t in items])
insights=section('insights','Latest Insights',articlecards(articles[:3])+link('Explore all planned insights →','/insights','text-link'),'Practical hardware topics in preparation. Articles will appear here once reviewed and published.')
final=section('contact','Where is your hardware program stuck?','<p>Tell me the product stage, biggest constraint and target timing. I’ll help identify the most useful next step.</p><div class="hero-actions">'+cta()+link('WhatsApp Dick',WA,'button button-quiet')+link('Connect on LinkedIn',LI,'button button-quiet')+'</div>')
schema={'@context':'https://schema.org','@graph':[{'@type':'Person','@id':'https://dickmui-consulting.vercel.app/#dick','name':'Dick Mui','jobTitle':'Hardware Commercialization & Program Leader','sameAs':[LI]},{'@type':'ProfessionalService','name':'Dick Mui Consulting','url':'https://dickmui-consulting.vercel.app/','areaServed':['United Kingdom','Europe','United States','Asia'],'founder':{'@id':'https://dickmui-consulting.vercel.app/#dick'}}]}
page('index','Dick Mui Consulting | Hardware Commercialization & Asia Manufacturing','Hardware commercialization, NPI, supplier strategy and production support for UK, EU and US product teams manufacturing across Asia.',hero+problem+service+work+process+execution+network+who+about+ways+partner+insights+final,schema=schema)
page('work','Selected Work | Dick Mui Consulting','Anonymised examples of supplier development, NPI, quality and production execution.',section('work','Selected Work',workcards)+final)
for c in cases: page('work/'+c['slug'],c['title']+' | Dick Mui Consulting',c['challenge'],section('case-study',esc(c['title']),'<div class="reading-column" data-case-study="'+c['slug']+'"><p class="eyebrow">Anonymised case study</p>'+casebody(c)+'</div>')+final)
page('insights','Hardware Insights | Dick Mui Consulting','Planned practical insights on suppliers, tooling, NPI and production readiness.',section('topics','Hardware Insights',articlecards(articles),'These topics are in preparation. No articles have been published yet.'))
for s,t in articles: page('insights/'+s,t+' | Dick Mui Consulting','A planned hardware insight by Dick Mui.',section('article',t,'<div class="reading-column"><p>Author: Dick Mui</p><p class="notice">Planned article — not yet published. Publication date and estimated reading time will be added when the article is ready.</p><!-- TODO: Approved article body, datePublished, readingMinutes and BlogPosting schema. Only published articles fire insight_read. --><h2>Working through a similar hardware problem?</h2>'+cta('Tell me where the program is stuck →')+'</div>')+section('related','Related planned insights',articlecards([(a,b) for a,b in articles if a!=s][:3])),noindex=True)
benefits=['Capability profile','Relevant project exposure','Qualified RFQ opportunities','Selected LinkedIn visibility','Case-study collaboration','Priority consideration where capability matches']
oldlinks=re.findall(r'<a href="(https://wa.me/[^"]+)"[^>]*>(.*?)</a>',re.search(r'<section class="partner-section".*?</section>',original,re.S)[0],re.S)
partnerbody=section('network','Our Partner Network','<p>Manufacturing, technology and ecosystem capabilities are considered against the needs of each project. Supplier identities remain private unless publication has been agreed.</p><div class="capability-tags">'+''.join('<span>'+esc(x)+'</span>' for x in caps)+'</div>'+cta('Discuss a Manufacturing Requirement')+f'<p class="independence">{independence}</p>')+section('apply','Become a Partner','<p>For manufacturers, technology companies and ecosystem partners. Possible benefits are subject to fit and an agreed scope; participation does not guarantee work.</p><ul>'+''.join('<li>'+x+'</li>' for x in benefits)+'</ul>'+link('Apply to Become a Partner','https://wa.me/85262568419?text=Hi%20Dick%2C%20I%20would%20like%20to%20apply%20to%20become%20a%20partner.','button button-primary','data-event="partner_apply_click"')+'<p>Start your application on WhatsApp with your company, capability, location and website.</p><details><summary>Partner participation enquiries</summary><p>Any commercially sponsored placement will be clearly identified.</p>'+''.join(link(label,url,'text-link') for url,label in oldlinks)+'</details>')
page('partners','Partner Network | Dick Mui Consulting','Explore manufacturing capabilities or enquire about joining Dick Mui’s partner network.',partnerbody)
def field(label,name,type='text',required=True): return f'<label>{label}{"" if required else " (optional)"}<input type="{type}" name="{name}" {"required" if required else ""} maxlength="{2000 if type=="url" else 200}" autocomplete="'+{'name':'name','company':'organization','email':'email'}.get(name,'off')+'"></label>'
def select(label,name,values): return f'<label>{label}<select name="{name}" required><option value="">Please select</option>'+''.join(f'<option>{esc(v)}</option>' for v in values)+'</select></label>'
challenges=['Supplier sourcing','Supplier performance','DFM','Tooling','Cost','Quality','Testing','Schedule','Pilot build','Mass-production readiness','Supply chain','Other']
form='<form id="project-form" class="project-form" action="/api/project" method="post"><p>All fields are required except LinkedIn and target production date. Please share a short, non-confidential summary; an NDA can be discussed before sensitive material is exchanged. Enquiries are forwarded by FormSubmit to Dick’s email inbox.</p><div class="form-grid">'+field('Name','name')+field('Company','company')+field('Work Email','email','email')+field('LinkedIn URL','linkedin','url',False)+select('What are you building?','product',['Consumer Electronics','IoT / Connected Device','Appliance','Industrial Product','Medical / Regulated','Other'])+select('Current stage','stage',['Concept','Prototype','EVT','DVT','Tooling','Pilot / PVT','Mass Production','Existing product / redesign'])+'</div><fieldset><legend>What’s the biggest challenge? Select at least one.</legend><div class="checkbox-grid">'+''.join(f'<label><input type="checkbox" name="challenges" value="{esc(c)}"> {c}</label>' for c in challenges)+'</div></fieldset><div class="form-grid">'+select('Expected production volume','volume',['<1,000','1,000–5,000','5,000–20,000','20,000–100,000','100,000+','Not sure yet'])+field('Target production date','targetDate','date',False)+'</div><label>Tell me briefly what’s happening<textarea name="message" required minlength="10" maxlength="5000" rows="6"></textarea></label>'+select('NDA required?','nda',['Yes','No','Not yet'])+'<div class="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div><input type="hidden" name="service"><input type="hidden" name="engagement"><label class="consent"><input type="checkbox" name="consent" required> I agree that Dick Mui may use these details to respond to my enquiry. <a href="/privacy">Privacy Policy</a></label><button class="button button-primary" type="submit">Send Project Brief</button><p id="form-status" role="status" aria-live="polite"></p><noscript><p>JavaScript is required for this form. Please contact Dick on WhatsApp instead.</p></noscript></form><div id="form-success" class="notice" hidden tabindex="-1"><h2>Thanks — your project brief has been received.</h2><p>I’ll review the stage, main constraint and likely next step before we speak.</p>'+link('Continue on WhatsApp',WA,'button button-primary')+link('Connect on LinkedIn',LI,'button button-quiet')+'</div>'
page('start-a-project','Start a Project | Dick Mui Consulting','Share your product stage, biggest constraint and target timing to discuss practical hardware support.',section('brief','Start a Project',form,'Tell me where your hardware program is stuck.')+section('direct','Prefer a direct conversation?',link('WhatsApp Dick',WA,'button button-quiet')+link('Connect on LinkedIn',LI,'button button-quiet')))
page('privacy','Privacy Policy | Dick Mui Consulting','How project enquiries are handled.',section('privacy','Privacy Policy','<div class="reading-column"><p class="notice">Preview draft — Dick must confirm the contact, retention and service-provider details before enabling the enquiry form in production.</p><h2>Project enquiries</h2><p>The form requests contact details and a brief project summary so Dick Mui can assess and respond to your enquiry. Do not include confidential technical documents or sensitive personal information.</p><h2>Tracking</h2><p>This version includes optional event hooks, with no analytics provider enabled. Form content and contact details are not included in analytics events.</p><h2>External services</h2><p>WhatsApp and LinkedIn links take you to those services, which have their own privacy policies. Fonts are requested from Google Fonts. Project enquiries are processed by FormSubmit and forwarded to Dick’s Gmail inbox. FormSubmit states that it retains submission records for 30 days. See <a href="https://formsubmit.co/privacy.pdf">FormSubmit’s privacy policy</a>.</p><h2>Questions and requests</h2><p>Contact Dick using the existing '+link('LinkedIn',LI)+' or '+link('WhatsApp',WA)+' links to ask about your enquiry information.</p><!-- TODO: Confirm controller/legal details, lawful basis, retention period, processors, international transfers and privacy contact before launch. --></div>'),noindex=True)
urls=['','work','partners','insights','start-a-project']+['work/'+c['slug'] for c in cases]
(P/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://dickmui-consulting.vercel.app/'+u+'</loc></url>' for u in urls)+'</urlset>')
(P/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: https://dickmui-consulting.vercel.app/sitemap.xml\n')
