const test=require('node:test'),assert=require('node:assert/strict');const handler=require('../api/project.js');
const valid={name:'Test User',company:'Test Company',email:'test@example.com',product:'IoT / Connected Device',stage:'Prototype',volume:'Not sure yet',nda:'Not yet',challenges:['DFM'],message:'Synthetic test enquiry only.',consent:'on'};
async function call(body=valid,method='POST',headers={}){let status=200,result;const res={setHeader(){},status(n){status=n;return this},json(o){result=o;return this}};await handler({method,headers:{'content-type':'application/json',host:'localhost',...headers},body},res);return{status,result};}
test('only POST accepted',async()=>assert.equal((await call(valid,'GET')).status,405));
test('cross-origin submissions rejected',async()=>assert.equal((await call(valid,'POST',{origin:'https://other.example'})).status,403));
test('invalid required fields, enums and challenges rejected',async()=>{for(const patch of [{email:'bad'},{stage:'fake'},{challenges:[]},{consent:''},{message:'short'},{linkedin:'https://evil.example'}])assert.equal((await call({...valid,...patch})).status,400);});
test('disabled delivery never claims receipt',async()=>{delete process.env.PROJECT_FORM_ENABLED;delete process.env.PROJECT_WEBHOOK_URL;assert.equal((await call()).status,503);});
test('only upstream success confirms receipt and payload is restricted',async()=>{process.env.PROJECT_FORM_ENABLED='true';process.env.PROJECT_WEBHOOK_URL='https://receiver.example';const original=global.fetch;try{let sent;global.fetch=async(url,opts)=>{sent=JSON.parse(opts.body);return{ok:true}};assert.deepEqual((await call({...valid,untrusted:'ignored'})).result,{ok:true});assert.equal(sent.untrusted,undefined);assert.equal(sent.email,valid.email);global.fetch=async()=>({ok:false});assert.equal((await call()).status,502);global.fetch=async()=>{throw Error('offline')};assert.equal((await call()).status,502);}finally{global.fetch=original;delete process.env.PROJECT_FORM_ENABLED;delete process.env.PROJECT_WEBHOOK_URL;}});
test('email delivery checks provider JSON and never treats activation as receipt',async()=>{process.env.PROJECT_FORM_ENABLED='true';process.env.PROJECT_DELIVERY_PROVIDER='formsubmit';process.env.PROJECT_EMAIL_TO='recipient@example.com';const original=global.fetch;try{let sent;global.fetch=async(url,opts)=>{assert.equal(url,'https://formsubmit.co/ajax/recipient%40example.com');sent=JSON.parse(opts.body);return{ok:true,json:async()=>({success:'false',message:'This form needs Activation.'})}};assert.equal((await call()).status,503);assert.equal(sent._replyto,valid.email);assert.equal(sent.challenges,'DFM');assert.equal(sent._captcha,undefined);global.fetch=async()=>({ok:true,json:async()=>({success:'true'})});assert.equal((await call()).status,200);global.fetch=async()=>({ok:true,json:async()=>({success:'false',message:'Rejected'})});assert.equal((await call()).status,502);global.fetch=async()=>({ok:true,json:async()=>{throw Error('Not JSON')}});assert.equal((await call()).status,502);}finally{global.fetch=original;delete process.env.PROJECT_FORM_ENABLED;delete process.env.PROJECT_DELIVERY_PROVIDER;delete process.env.PROJECT_EMAIL_TO;}});
